##
# Pokémon Trainers
##

ash:
  # 025
  pikachu:
    primary: '#F6BD20'
    secondary: '#4C1803'
    tertiary: '#DE7329'
    unibody: '#F7DE82'

  # 010
  caterpie:
    primary: '#F47B59'
    secondary: '#63583E'
    tertiary: '#F2DF9C'
    unibody: '#8CC979'

  # 011
  metapod:
    primary: '#77A052'
    secondary: '#230729'
    tertiary: '#DDFEAC'
    unibody: '#85B243'

  # 012
  butterfree:
    primary: '#7FBBC5'
    secondary: '#262330'
    tertiary: '#F4D89A'
    unibody: '#978DC1'

  # 016
  pidgey:
    primary: '#F3EAB7'
    secondary: '#0A0A08'
    tertiary: '#AC8992'
    unibody: '#9E6B35'

  # 017
  pidgeotto:
    primary: '#A3733C'
    secondary: '#C25046'
    tertiary: '#A48554'
    unibody: '#F7F3B0'

  # 001
  bulbasaur:
    primary: '#5B9C71'
    secondary: '#0F2C33'
    tertiary: '#F8DEA0'
    unibody: '#77AC98'

  # 004
  charmander:
    primary: '#96191B'
    secondary: '#35261D'
    tertiary: '#F6DFD1'
    unibody: '#F4B186'

  # 005
  charmeleon:
    primary: '#BE5B55'
    secondary: '#532924'
    tertiary: '#EAD3D1'
    unibody: '#D3675A'

  # 006
  charizard:
    primary: '#CF844B'
    secondary: '#4C1803'
    tertiary: '#DBD8AE'
    unibody: '#DC8E4C'

  # 007
  squirtle:
    primary: '#916A5B'
    secondary: '#832900'
    tertiary: '#B4E6EE'
    unibody: '#84C1D4'

  # 020
  raticate:
    primary: '#A28091'
    secondary: '#2E2300'
    tertiary: '#21C8D8'
    unibody: '#CB9652'

  # 128
  tauros:
    primary: '#6E6852'
    secondary: '#3D2914'
    tertiary: '#23809D'
    unibody: '#EAA763'

  # 143
  snorlax:
    primary: '#F5EF7C'
    secondary: '#1A2927'
    tertiary: '#40C9B2'
    unibody: '#4A736B'

brock:
  # 095
  onix:
    primary: '#4B494E'
    secondary: '#E8E8D6'
    tertiary: '#4E7378'
    unibody: '#9B9AA2'

  # 074
  geodude:
    primary: '#505833'
    secondary: '#382C00'
    tertiary: '#A6552D'
    unibody: '#B5A66D'

  # 041
  zubat:
    primary: '#874E83'
    secondary: '#F5F56E'
    tertiary: '#5C421B'
    unibody: '#5486A9'

  # 042
  golbat:
    primary: '#82487A'
    secondary: '#F5F56E'
    tertiary: '#5C421B'
    unibody: '#306E93'

  # 037
  vulpix:
    primary: '#723822'
    secondary: '#421402'
    tertiary: '#f2a485'
    unibody: '#c08672'

  # 038
  ninetales:
    primary: '#DDCA6B'
    secondary: '#737358'
    tertiary: '#AA7BD9'
    unibody: '#F2F3BA'

  # 081
  magnemite:
    primary: '#93928E'
    secondary: '#1A2342'
    tertiary: '#7E6A85'
    unibody: '#9DBBC5'

misty:
  # 055
  psyduck:
    primary: '#66431b'
    secondary: '#623108'
    tertiary: '#C16200'
    unibody: '#FFD54B'

  # 060
  poliwag:
    primary: '#C8DAE8'
    secondary: '#060329'
    tertiary: '#94C6FF'
    unibody: '#5B89BD'

  # 061
  poliwhirl:
    primary: '#E0E4EF'
    secondary: '#060329'
    tertiary: '#94C6FF'
    unibody: '#5C86B8'

lt.surge:
  # 025
  pikachu:
    primary: '#F6BD20'
    secondary: '#4C1803'
    tertiary: '#DE7329'
    unibody: '#F7DE82'

  # 026
  raichu:
    primary: '#66431b'
    secondary: '#623108'
    tertiary: '#C16200'
    unibody: '#F2BD4B'

  # 125
  electabuzz:
    primary: '#0A162C'
    secondary: '#377B9C'
    tertiary: '#FCFBD8'
    unibody: '#F8D871'

  # 082
  magneton:
    primary: '#91918F'
    secondary: '#1A2342'
    tertiary: '#B5249A'
    unibody: '#A3BEC7'

erika:
  # 069
  bellsprout:
    primary: '#93CF9C'
    secondary: '#1F1E0C'
    tertiary: '#0078FC'
    unibody: '#DEDA6C'

  # 070
  weepinbell:
    primary: '#79B47C'
    secondary: '#786548'
    tertiary: '#0078FC'
    unibody: '#EBEB73'

  # 071
  victreebel:
    primary: '#88CA8D'
    secondary: '#DB8570'
    tertiary: '#66916C'
    unibody: '#EAEA6E'

  # 003
  venusaur:
    primary: '#548B52'
    secondary: '#C9F3F1'
    tertiary: '#142625'
    unibody: '#58A7A2'

koga:
  # 042
  golbat:
    primary: '#82487A'
    secondary: '#F5F56E'
    tertiary: '#5C421B'
    unibody: '#306E93'

  # 123
  scyther:
    primary: '#6A9B40'
    secondary: '#1D300C'
    tertiary: '#4C57B8'
    unibody: '#80C342'
